service_implementation.py: Add Exception Handling
honeynet/checkpot pull request #2
Opened 2018-12-31 14:34 UTC by sladyn98

Added Exception hadling to the HTTP tests

2019-01-10 07:33 UTC, glaslos commented on .travis.yml
> +  - 2.7.9
This tool should be tested with Python 3.6

2019-01-10 07:49 UTC, glaslos requested changes

2019-01-10 07:49 UTC, glaslos commented on .travis.yml
> +  - hg clone --config ui.tls=false https://vladflorea@bitbucket.org/vladflorea/python-nmap
you want to keep this requirement in the requirements.txt

2019-01-10 08:02 UTC, sladyn98 commented
Yeah yeah i pushed these changes here by mistake  I will revert them soon
Sorry.

2019-06-30 19:23 UTC, sladyn98 commented
@glaslos Does this need any more reviews.

2019-11-11 15:24 UTC, closed without merging